# Generated by Django 4.1.7 on 2023-03-25 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_var', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=80)),
                ('value_var', models.FloatField()),
                ('exp_var', models.TextField()),
                ('string_var', models.CharField(max_length=80)),
                ('money', models.BooleanField(default=False)),
                ('save_value_with_result', models.BooleanField(default=True)),
                ('expression_recursive', models.BooleanField(default=True)),
                ('expression_is_html', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default='MarcioSmall', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
